llm:
  model_name: "gemma-3-1b-it"
  base_url: "http://127.0.0.1:1234/v1/chat/completions"  # Use /v1/completions
  api_key: "lm-studio"  # Placeholder; LM Studio doesn't require an API key
  temperature: 0.7
  max_tokens: 500
  timeout: 60